apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: counter-server

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
