apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-094d7f9dc550f7c3e
    fsType: ext4